### PR TITLE
fix: addModules even when there is no <math>

### LINKED ISSUE #36: $wgSmjExtraInlineMath doesn't do anything if there isn't a `<math>` tag on the page.
The title is saying it all. The script isn't even getting loaded if mediawiki doesn't see a `<math>` tag.

### PR DESCRIPTION
**Pull request by cubercsl**
In version 0.7.x, the module will always be loaded even without any `<math>` tag. But in the master code, it will only be loaded when there are one or more `<math>` tags, which prevents the formulas of many pages that only use `$` from being loaded correctly. 

Maybe introduced from c4bd866.

Fix #36

### CODE REVIEW

File: SimpleMathJaxHooks.php [hunk 1]
```diff
@@ -13,6 +13,8 @@ public static function onParserFirstCallInit( Parser $parser ) {
 		$wgOut->addJsConfigVars( 'wgSmjScale', $wgSmjScale );
 		$wgOut->addJsConfigVars( 'wgSmjEnableMenu', $wgSmjEnableMenu );
 		$wgOut->addJsConfigVars( 'wgSmjDisplayAlign', $wgSmjDisplayAlign );
+		$wgOut->addModules( 'ext.SimpleMathJax' );
+		$wgOut->addModules( 'ext.SimpleMathJax.mobile' ); // For MobileFrontend
```
Comment (noloader) [inline SimpleMathJaxHooks.php:17]: `addModules` needs an array. Use `[` and `]`.

Also see GH #37.

**Comment by noloader** [comment]
@jmnote,

Are you still around?

**Comment by noloader** [comment]
@cubercsl,

I'm not sure how we a re different with respect to out configurations (LocalSettings.php?), but the change results in:

```
MediaWiki internal error.

Original exception: [YsMvugTdq3nFvHWC1gShnQAAAAc] /wiki/Main_Page Error: Call to a member function addModules() on null
Backtrace:
from /var/www/html/w/extensions/SimpleMathJax/SimpleMathJaxHooks.php(20)
#0 /var/www/html/w/includes/HookContainer/HookContainer.php(338): SimpleMathJaxHooks::onParserFirstCallInit()
#1 /var/www/html/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#2 /var/www/html/w/includes/HookContainer/HookRunner.php(2872): MediaWiki\HookContainer\HookContainer->run()
#3 /var/www/html/w/includes/parser/Parser.php(533): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit()
#4 /var/www/html/w/includes/parser/ParserFactory.php(196): Parser->__construct()
#5 /var/www/html/w/includes/ServiceWiring.php(1211): ParserFactory->create()
#6 /var/www/html/w/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#7 /var/www/html/w/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService()
#8 /var/www/html/w/includes/MediaWikiServices.php(294): Wikimedia\Services\ServiceContainer->getService()
#9 /var/www/html/w/includes/MediaWikiServices.php(1366): MediaWiki\MediaWikiServices->getService()
#10 /var/www/html/w/includes/cache/MessageCache.php(1270): MediaWiki\MediaWikiServices->getParser()
#11 /var/www/html/w/includes/cache/MessageCache.php(1249): MessageCache->getParser()
#12 /var/www/html/w/includes/language/Message.php(1474): MessageCache->transform()
#13 /var/www/html/w/includes/language/Message.php(1007): Message->transformText()
#14 /var/www/html/w/includes/language/Message.php(1071): Message->format()
#15 /var/www/html/w/includes/OutputPage.php(1041): Message->text()
#16 /var/www/html/w/includes/OutputPage.php(1090): OutputPage->setHTMLTitle()
#17 /var/www/html/w/includes/page/Article.php(464): OutputPage->setPageTitle()
#18 /var/www/html/w/includes/actions/ViewAction.php(80): Article->view()
#19 /var/www/html/w/includes/MediaWiki.php(543): ViewAction->show()
#20 /var/www/html/w/includes/MediaWiki.php(321): MediaWiki->performAction()
#21 /var/www/html/w/includes/MediaWiki.php(912): MediaWiki->performRequest()
#22 /var/www/html/w/includes/MediaWiki.php(563): MediaWiki->main()
#23 /var/www/html/w/index.php(53): MediaWiki->run()
#24 /var/www/html/w/index.php(46): wfIndexMain()
#25 {main}

Exception caught inside exception handler: [YsMvugTdq3nFvHWC1gShnQAAAAc] /wiki/Main_Page Error: Call to a member function addModules() on null
Backtrace:
from /var/www/html/w/extensions/SimpleMathJax/SimpleMathJaxHooks.php(20)
#0 /var/www/html/w/includes/HookContainer/HookContainer.php(338): SimpleMathJaxHooks::onParserFirstCallInit()
#1 /var/www/html/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#2 /var/www/html/w/includes/HookContainer/HookRunner.php(2872): MediaWiki\HookContainer\HookContainer->run()
#3 /var/www/html/w/includes/parser/Parser.php(533): MediaWiki\HookContainer\HookRunner->onParserFirstCallInit()
#4 /var/www/html/w/includes/parser/ParserFactory.php(196): Parser->__construct()
#5 /var/www/html/w/includes/ServiceWiring.php(1211): ParserFactory->create()
#6 /var/www/html/w/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}()
#7 /var/www/html/w/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService()
#8 /var/www/html/w/includes/MediaWikiServices.php(294): Wikimedia\Services\ServiceContainer->getService()
#9 /var/www/html/w/includes/MediaWikiServices.php(1366): MediaWiki\MediaWikiServices->getService()
#10 /var/www/html/w/includes/cache/MessageCache.php(1270): MediaWiki\MediaWikiServices->getParser()
#11 /var/www/html/w/includes/cache/MessageCache.php(1249): MessageCache->getParser()
#12 /var/www/html/w/includes/language/Message.php(1474): MessageCache->transform()
#13 /var/www/html/w/includes/language/Message.php(1007): Message->transformText()
#14 /var/www/html/w/includes/language/Message.php(1071): Message->format()
#15 /var/www/html/w/includes/OutputPage.php(1041): Message->text()
#16 /var/www/html/w/includes/OutputPage.php(1090): OutputPage->setHTMLTitle()
#17 /var/www/html/w/includes/OutputPage.php(2843): OutputPage->setPageTitle()
#18 /var/www/html/w/includes/exception/MWExceptionRenderer.php(148): OutputPage->prepareErrorPage()
#19 /var/www/html/w/includes/exception/MWExceptionRenderer.php(76): MWExceptionRenderer::reportHTML()
#20 /var/www/html/w/includes/exception/MWExceptionHandler.php(107): MWExceptionRenderer::output()
#21 /var/www/html/w/includes/exception/MWExceptionHandler.php(202): MWExceptionHandler::report()
#22 /var/www/html/w/includes/MediaWiki.php(585): MWExceptionHandler::handleException()
#23 /var/www/html/w/index.php(53): MediaWiki->run()
#24 /var/www/html/w/index.php(46): wfIndexMain()
#25 {main}
```

**Comment by cubercsl** [comment]
@noloader This PR has been open for a while and it worked for me at that moment. Since I don't have the latest environment now, the last commit is a hotfix without any test. I'll take a closer look this weekend.

**Comment by noloader** [comment]
@cubercsl,

My bad. It was my mistake. It was a copy/paste, and I continued to use `$parser`.
